[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
optimizer = true
optimizer_runs = 1000
fs_permissions = [{ access = "read", path = "./"}]

[profile.default.rpc_endpoints]
anvil = "http://127.0.0.1:8545"
